---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argus-config
  namespace: argus
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDpzCCAo+gAwIBAgIUZvcHeGu0R2AmNnXfjVOEt+p77F0wDQYJKoZIhvcNAQEM
    BQAwYzELMAkGA1UEBhMCVVMxDTALBgNVBAgMBE9oaW8xETAPBgNVBAcMCENvbHVt
    YnVzMRYwFAYDVQQKDA1DbHVzdGVyR2FyYWdlMQ0wCwYDVQQLDARUZXN0MQswCQYD
    VQQDDAJjYTAeFw0xODEwMjkyMTQwNTdaFw0xOTEwMjkyMTQwNTdaMGMxCzAJBgNV
    BAYTAlVTMQ0wCwYDVQQIDARPaGlvMREwDwYDVQQHDAhDb2x1bWJ1czEWMBQGA1UE
    CgwNQ2x1c3RlckdhcmFnZTENMAsGA1UECwwEVGVzdDELMAkGA1UEAwwCY2EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCaCreSdSSPDKGQjIazb6Z3V0Kt
    r4huotAFEyBHlnanxc/CLyJu+kQZW8WIBX370KSjgkMt7n9U539gyxtp4EBHY+Hx
    sAVQzCELHwYSwfRsigCNX6O0gqxwXn8KrUT3lZUQ55Q38TaUpVBmex0l1VUfwB4X
    MyelWlF0dEPibxhX6QWa7EDcj52k1SHvUtVW6hDZtILkVCjQT0YshbBbz55Ozfzm
    dXe2zFT0GtRBF8NGASdZJf3y92Ix99rF+g0rm020eXmwmszhkiL7cw2k6KVT2d8O
    jRsASmQZxG6tUiEnppmwM1PYDI+0TUWXaRMVR3mNaIJQJ6PckpDcbnsVFKcrAgMB
    AAGjUzBRMB0GA1UdDgQWBBRs6kUP/t6pZaPlUGcfeJb+hcj43zAfBgNVHSMEGDAW
    gBRs6kUP/t6pZaPlUGcfeJb+hcj43zAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
    DQEBDAUAA4IBAQB+3BxNvKYGe4jbonMEwkAUVNd34RBRgRtVJEKyo81Oe3VKwFBu
    /isRkgJimqO5DUjPLpnXsO3H+S/3tDQBzJYL/bS/r3mX34L01btrm9BhAMzOI31J
    JhXxOvYLXefOhD+QaFjGowWy1tGYrBVSZGj24mFHiHNTiqbBU0CWEXAh1NlIXM0t
    7UuQhHcDlotYRuiFIUWmp0b6hZgrJ0FDJu1YFw+6Gwh3Z1kKezmeAq9GBTbDKg9c
    jQW4inX2n/+yxxFp3f8xLG9gh0FFhNpSh6DwA0S5GoGrOgSE/ZeoDe9EHMSJ5Lll
    OCuLTQ9e8MfVlVgNZntXazXnVPNmNOgeeise
    -----END CERTIFICATE-----
  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDVjCCAj4CFE+FI82N+qiTyrEvOAJs1rB2K6EfMA0GCSqGSIb3DQEBDAUAMGMx
    CzAJBgNVBAYTAlVTMQ0wCwYDVQQIDARPaGlvMREwDwYDVQQHDAhDb2x1bWJ1czEW
    MBQGA1UECgwNQ2x1c3RlckdhcmFnZTENMAsGA1UECwwEVGVzdDELMAkGA1UEAwwC
    Y2EwHhcNMTgxMDI5MjE0MDU3WhcNMTkxMDI5MjE0MDU3WjBsMQswCQYDVQQGEwJV
    UzENMAsGA1UECAwET2hpbzERMA8GA1UEBwwIQ29sdW1idXMxFjAUBgNVBAoMDUNs
    dXN0ZXJHYXJhZ2UxDzANBgNVBAsMBlNlcnZlcjESMBAGA1UEAwwJbG9jYWxob3N0
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+J6rI5mSVWBKrmPL4EX8
    J64tRUeQvC5KX83WjFIovBQd1SSikeKfSkfYgW5VyA6NmJglhjVxPGtMIJXV6GW2
    69nIHrZHt4wqPyioavimlyq5t4EAjHs/Jo/7AALStW9OVVdcDJNDfxWDqywnuEsK
    Hmsfa1S7Acai52lvbUcF9BJRt3dQFSh1rhfMFJ1wO+zfQ269KH50tqGXuezG/4Bk
    DXDzXYKBs+EPN7wV7pBzWde1VAtSJRWKcaYgqY3U0jf7Qfs8ZF7+nrqc5XmbRUKq
    sS3tI42ELd0rNX4Lw5N9VXvA13OigS8iwYxv36FPUWaNHFrsCiQD/cKdhngtkNCN
    4QIDAQABMA0GCSqGSIb3DQEBDAUAA4IBAQAOHyFMTGEldJ8cg5eZlk5QOY6vVXFT
    mqaobgCU50L2DsMRuTi62ikaqbmMTOUHS/7n/3RtrCOib0qhyTZwzVCH19RLrbEA
    Bn9JvK05EVRAbQGU1X+bJf1davHQ6sa2iI+ztxn0TnnJtnBGHv0BUziAV+Azervv
    2g9gq7zmiuksYg9nklupcOmK76OCqo9O+43rWQWvkEyZAOhwmjglqB1Ik6nUt7Xf
    KB01VoBnH5qIQpTPhpsuiHGF7ivpJAOLFDra4K4a31G4R9cigQZE4QKL6xPyC0aP
    Aoci5lghy+JEiV1MqB95qzfCFxEpHQIWmfhorK6CcPx7SNhm+HNsrXdi
    -----END CERTIFICATE-----
  key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA+J6rI5mSVWBKrmPL4EX8J64tRUeQvC5KX83WjFIovBQd1SSi
    keKfSkfYgW5VyA6NmJglhjVxPGtMIJXV6GW269nIHrZHt4wqPyioavimlyq5t4EA
    jHs/Jo/7AALStW9OVVdcDJNDfxWDqywnuEsKHmsfa1S7Acai52lvbUcF9BJRt3dQ
    FSh1rhfMFJ1wO+zfQ269KH50tqGXuezG/4BkDXDzXYKBs+EPN7wV7pBzWde1VAtS
    JRWKcaYgqY3U0jf7Qfs8ZF7+nrqc5XmbRUKqsS3tI42ELd0rNX4Lw5N9VXvA13Oi
    gS8iwYxv36FPUWaNHFrsCiQD/cKdhngtkNCN4QIDAQABAoIBAQD3kK/jvClt4Hud
    GXzLL4U+Uf98TB4AdKvUqFgq1CkB15o5QsirMhnh0pbxk1fR5UP0HhTHhnHicwmU
    LP+a8aXrRqoygtn5GJZ829SQ6FaikoXqB4fvW05v7NFImocM6e/7pQjg8Mc2Rcsd
    6NMIfZhu38aijvXEd/KBMoklLKLt/FV5woVY33DHjeAqqxKGghmR/2MtelLygyXN
    0tTiEvVgYH+ky/K51PC9AyQnMhPLF5UYNJ+Po6EAElxfhGwd7gBBiYGEgLRjcn8r
    lzPVtd6Yxq/5dhY0d3h6ggIBB18g/pOwYkrAUwcR1+2evaUsBot6Zw3gS6Qif2K3
    pPMdCJPdAoGBAPyFBRd18mmO9EL/eMBGU9o6Z/NpE8m2wdwIEGDyvkVfETN3vLJW
    LyGNjt2FtbcOPj5spgH2G6mQeMJFTEzovByJF3XBNOy9+MOmXcDAVBKMLntvpkrE
    41tZF5M2jNkXbQd+ZDCz+jspwK4CV5LeDwrlUrAcvAQxrHepRbkdoWdDAoGBAPwL
    44EXOx/2nQfSvJgiPLIPJXPAgFcGLHRkvVC1wyVXPpkBZRs0+jRMpyUrs1WsY9Gr
    0iIp6zdgEU6VRcXeK4KVp+PIsXR6SxgiEQ5pKtkIkGTKyOv0nTq9ERSk4xWcXA5X
    EE2YagCnCkEGNb/pao1RGOev5+/MozlMMeQU/YoLAoGBAPVVZzT76qCTusy819w2
    d5E13XinRgpb/MyBKSiHrkRHsLaIRlQdV30JwxuFpJ5MwDx14nNVYFrFeg2EtjSi
    iOBQcPJ+26SGjQHIyJ1UPlomx6I1PyK1Vw6Q6E6mWQExuUPmkAChWyPP1Ns6e0q9
    Y2/6jPN9d0271QwM8SiAmSdxAoGAUPOckWSdt8lkbBPSQOaWKfZVaBUG42x3MLb+
    WwLV95NK5qedCpz8U3nfIUAk7DpfIQOXjSN7iaCQTnYBH+kYfmuErdNSs39nyQuA
    AOnkOirW/Zhn6ej56ti4uLGwwcsjgfOSp+lw+l6sG3BcKRRWBadrYVaNHubR8eA4
    EfJv8DsCgYEAln6sEz29SqqujDxznkwKs1TFZNAnnRQJ3yDXFMlBUgUlp0MblOka
    HzXAb31lv/DAm+7Xl3szpm3IkF2EFUXvPAaZlc6VEE1nM0O2cWBgFfrsLopzZ5RL
    fV+8qx1qHmRx+A7eQ6YIounHRxlXmgsc8nZ4UpDd4UNv3zz467Y2PkM=
    -----END RSA PRIVATE KEY-----
